### PR TITLE
Issue/9/console does not exit

### LINKED ISSUE #9: Console does not exit
Whenever the code is run I notice that something does not properly exit.

Try this code out:
```
from ergpy import helper_functions, appkit

node_url: str = "http://213.239.193.208:9052/"  # MainNet or TestNet
ergo = appkit.ErgoAppKit(node_url=node_url)
wallet_mnemonic = "what stadium typical spell rate truly pen tongue fuel intact fluid strike vibrant city shine"
receiver_addresses = [
    "3WwdXmYP39DLmDWJ6grH9ArXbWuCt2uGAh46VTfeGPrHKJJY6cSJ",
    "3WwuG9amNVDwkJdgT5Ce7aJCfeoafVmd9tag9AEiAZwgPi7pYX3w",
    "3Wxk5oofZ3Laq2CpFW4Fi9YQiaep9bZr6QFg4s4xpzz4bi9tZq2U"
]

amount = [0.22, 0.33, 0.11]

tx = helper_functions.simple_send(ergo=ergo, amount=amount, wallet_mnemonic=wallet_mnemonic, receiver_addresses=receiver_addresses)

data = f'Transaction: {str(tx)}'
with open('demo.text', 'w') as file:
    file.write(data)
print("wrote to file")

```
This will write the txid to file and print to console. However if you want to exit to run other commands in the console you must exit with `ctrl + c`.  I tried including `sys.exit(0)` and `quit()` in the code but it does not help.

Any ideas @rafidini ?

Thank you

### PR DESCRIPTION
**Pull request by rafidini**
## Commits
0dd071bce344162dd0caefe2686858c10c620737
83fa553e2513a8001efa2fbdd5232c0c3c075316
bd898c5b9506f73d4b727754b08613c073b7682a

fix #9

### CODE REVIEW

**Comment by rafidini** [comment]
@mgpai22 can you test first before the merging please.

**Comment by mgpai22** [comment]
I tried this out. Unfortunately it seems that the functions don't print the txid to console after submission. 

I made this function though using parts of your code:
```
@initialize_jvm
def exit():
    return jpype.java.lang.System.exit(0)
```
it allows the console to exit after printing the txid. However it needs to be called each time after a transaction is sent.

**Comment by rafidini** [comment]
> I tried this out. Unfortunately it seems that the functions don't print the txid to console after submission.
> 
> I made this function though using parts of your code:
> 
> ```
> @initialize_jvm
> def exit():
>     return jpype.java.lang.System.exit(0)
> ```
> 
> it allows the console to exit after printing the txid. However it needs to be called each time after a transaction is sent.

I will check that out

**Comment by rafidini** [comment]
Yo @mgpai22 now can you check ?

**Comment by mgpai22** [comment]
Yes this works well! Although in the future it may be nice not having to explicitly call that exit function.

**Pull request merged**
